notifications:
  irc:
    channels:
      - "chat.freenode.net#noosfero"
      - "chat.freenode.net#noosfero-br"
    template:
      - "%{repository_slug} %{branch} %{commit} %{commit_subject} - %{result} %{build_url}"

dist: trusty
language: ruby
rvm:
  - 2.3.0

sudo: false
addons:
  apt:
    packages:
      - po4a
      - iso-codes
      - tango-icon-theme
      - pidgin-data
      # for gem extensions
      - libmagickwand-dev
      - libpq-dev
      - libreadline-dev
      - libxslt1-dev
  artifacts:
    paths:
      - $(ls tmp/artifact* | tr "\n" ":")

# workaround for https://github.com/travis-ci/travis-ci/issues/4536
before_install:
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.3.0
  - gem install bundler
cache: bundler

before_script:
  - mkdir -p tmp/{pids,cache} log cache
  - script/noosfero-plugins disableall
  #- bundle exec rake makemo &>/dev/null
# database
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database myapp_test;' -U postgres
  - bundle exec rake db:schema:load &>/dev/null
  - bundle exec rake db:migrate &>/dev/null

env:
  - TASK=test:units
  - TASK=test:functionals
  - TASK=test:integration
  - TASK=cucumber LANG=en
  - SLICE=1/3 TASK=selenium
  - SLICE=2/3 TASK=selenium
  - SLICE=3/3 TASK=selenium
  - SLICE=1/4 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=2/4 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=3/4 TASK=test:noosfero_plugins BUNDLE_OPTS=install
  - SLICE=4/4 TASK=test:noosfero_plugins BUNDLE_OPTS=install

script:
  - bundle exec rake $TASK

