notifications:
  irc:
    channels:
      - "chat.freenode.net#noosfero"
      - "chat.freenode.net#noosfero-br"
    template:
      - "%{repository_slug} %{branch} %{commit} %{commit_subject} - %{result} %{build_url}"

# Ensure Container-based environment for faster boot times.
# See https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
# Stick with precise as trusty is at least 50% slower.
#dist: trusty

cache: bundler

language: ruby
rvm:
  - 2.4.1
jdk:
  - openjdk8

services:
  - postgresql

addons:
  apt:
    packages:
      - tango-icon-theme
      - pidgin-data
  artifacts:
    paths:
      - $(ls tmp/artifact* | tr "\n" ":")
  # same as in docker ci image
  firefox: '45.7.0'
  postgresql: '9.4'

before_install:
  # geckodriver, from http://www.columbia.edu/~njn2118/journal/2016/10/28.html
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.14.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  # elasticsearch 2
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &

before_script:
  - mkdir -p tmp/{pids,cache} log cache
  - script/noosfero-plugins disableall
  #- bundle exec rake makemo &>/dev/null
# database
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database myapp_test;' -U postgres
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate &>/dev/null

env:
  global:
    - ES_VERSION=1.7.6
    - ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
    - LANG=en
  matrix:
    - TASK=spec SPEC=spec/models
    - TASK=test:api
    - TASK=test:units
    - TASK=test:functionals
    - TASK=test:integration
    - SLICE=1/2 TASK=cucumber
    - SLICE=2/2 TASK=cucumber
    - SLICE=1/4 TASK=selenium
    - SLICE=2/4 TASK=selenium
    - SLICE=3/4 TASK=selenium
    - SLICE=4/4 TASK=selenium
    - SLICE=1/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=2/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=3/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=4/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    - SLICE=5/5 TASK=test:noosfero_plugins NOOSFERO_BUNDLE_OPTS=install
    # chrome hanging on travis
    #- SLICE=1/4 TASK=selenium SELENIUM_DRIVER=chrome
    #- SLICE=2/4 TASK=selenium SELENIUM_DRIVER=chrome
    #- SLICE=3/4 TASK=selenium SELENIUM_DRIVER=chrome
    #- SLICE=4/4 TASK=selenium SELENIUM_DRIVER=chrome

matrix:
  allow_failures:
    - env: SLICE=1/4 TASK=selenium SELENIUM_DRIVER=chrome
    - env: SLICE=2/4 TASK=selenium SELENIUM_DRIVER=chrome
    - env: SLICE=3/4 TASK=selenium SELENIUM_DRIVER=chrome
    - env: SLICE=4/4 TASK=selenium SELENIUM_DRIVER=chrome

script:
  - bundle exec rake $TASK

